name: Build and Push Docker Image

on:
  push:
    branches: [cicd]
env:
    REGION: europe-west3
    GCP_PROJECT_ID: vibrant-sound-469408
    REPO: wahr-oder-watt
    IMAGE: wowapp
    VERSION: 1.0.0
    GAR_LOCATION: europe-west3-docker.pkg.dev/vibrant-sound-469408/wahr-oder-watt

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v3'
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          service_account: ${{ secrets.GCP_SA }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure Docker auth for Artifact Registry
        run: |
            gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.GAR_LOCATION }}/${{ env.IMAGE }}:${{ env.VERSION }}

