name: Build and Push Docker Image

on:
  push:
    branches: [cicd]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v3'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}
    
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure Docker auth for Artifact Registry
        run: |
            gcloud auth configure-docker ${REGION}-docker.pkg.dev --quiet
        env:
          REGION: ${{ secrets.GCP_REGION }}

      - name: Build and push Docker image
        run: |
          IMAGE="${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/wowapp:latest"
          docker buildx build \
            --platform linux/amd64 \
            -t $IMAGE \
            --push .
        env:
          REGION: ${{ secrets.GCP_REGION }}
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          REPO: ${{ secrets.GCP_ARTIFACT_REPO }}