name: Build and Push Docker Image

on:
  push:
    branches: [cicd]
env:
    REGION: europe-west3
    GCP_PROJECT_ID: vibrant-sound-469408
    REPO: wahr-oder-watt
    IMAGE: wowapp
    VERSION: 1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v3'
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}
    
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Verify
        run: |
            gcloud auth list
            gcloud config list project
        
      - name: Check Artifact Registry access
        run: |
          gcloud artifacts repositories list \
            --location=europe-west3 \
            --project=${{ env.GCP_PROJECT_ID }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure Docker auth for Artifact Registry
        run: |
            gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE }}:${{ env.VERSION }}

